# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Check formatting
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - uses: actions/checkout@v3
      - name: Install Clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    needs: [fmt, lint]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --all -- --nocapture